# Generated by Django 5.1.1 on 2025-11-09 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('waste_type', models.CharField(choices=[('kitchen', 'Kitchen Waste'), ('food', 'Food Waste'), ('customer', 'Customer Waste')], default='kitchen', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('kitchen', 'Kitchen Waste'), ('food', 'Food Waste'), ('customer', 'Customer Waste')], max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('donated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donation_drive.donationdrive')),
            ],
        ),
    ]
