# Generated by Django 5.1.1 on 2025-11-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_drive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
    ]
