# Generated by Django 5.1.1 on 2025-11-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='waste_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen Waste'), ('food', 'Food Waste'), ('customer', 'Customer Waste'), ('recyclable', 'Recyclable Waste'), ('biodegradable', 'Biodegradable Waste')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='waste_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen Waste'), ('food', 'Food Waste'), ('customer', 'Customer Waste'), ('recyclable', 'Recyclable Waste'), ('biodegradable', 'Biodegradable Waste')], default='kitchen', max_length=50),
        ),
    ]
