# Generated by Django 5.1.1 on 2025-11-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_drive', '0002_remove_donation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdrive',
            name='collected_amount',
        ),
        migrations.RemoveField(
            model_name='donationdrive',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='donationdrive',
            name='target_amount',
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='waste_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen Waste'), ('food', 'Food Waste'), ('customer', 'Customer Waste')], default='kitchen', max_length=50),
        ),
    ]
