# Generated by Django 5.1.1 on 2025-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_pickups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashpickup',
            name='waste_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen Waste'), ('food', 'Food Waste'), ('customer', 'Customer Waste')], max_length=50),
        ),
    ]
