# Generated by Django 5.1.1 on 2025-11-09 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('trash_pickups', '0002_alter_trashpickup_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashpickup',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='drivers.driver'),
        ),
    ]
