# Generated by Django 5.1.1 on 2025-11-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_pickups', '0003_trashpickup_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashpickup',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Pickup latitude coordinate', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trashpickup',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Pickup longitude coordinate', max_digits=20, null=True),
        ),
    ]
