# Generated by Django 5.1.1 on 2025-11-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_pickups', '0004_trashpickup_latitude_trashpickup_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trashpickup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='trashpickup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trashpickup',
            name='points_awarded',
            field=models.IntegerField(default=0, help_text='Reward points earned when completed (for reference only)'),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='waste_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen Waste'), ('food', 'Food Waste'), ('customer', 'Customer Waste'), ('recyclable', 'Recyclable Waste'), ('biodegradable', 'Biodegradable Waste')], max_length=50),
        ),
    ]
