# Generated by Django 5.1.1 on 2025-11-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_pickups', '0005_alter_trashpickup_options_trashpickup_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashpickup',
            name='segregation_score',
            field=models.FloatField(default=0.0),
        ),
    ]
