# Generated by Django 5.1.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_pickups', '0006_trashpickup_segregation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashpickup',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pickup_proofs/'),
        ),
    ]
