# Generated by Django 5.1.1 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trash_pickups", "0007_trashpickup_proof_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trashpickup",
            name="weight_kg",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="trashpickup",
            name="actual_weight_kg",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="trashpickup",
            name="estimated_weight_kg",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
