# Generated by Django 5.1.1 on 2025-11-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='default123', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='username',
            field=models.CharField(default='driver1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
