# Generated by Django 5.1.1 on 2025-11-09 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('deducted', 'Deducted'), ('used_in_recipe', 'Used in Recipe'), ('adjusted', 'Adjusted')], max_length=20)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='food_menu.ingredient')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_menu.unittype')),
            ],
        ),
    ]
