# Generated by Django 5.1.1 on 2025-11-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0002_ingredienthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienthistory',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='ingredienthistory',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingredienthistory',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredienthistory',
            name='change_type',
            field=models.CharField(choices=[('added', 'Added'), ('deducted', 'Deducted'), ('used_in_recipe', 'Used in Recipe')], max_length=20),
        ),
    ]
