# Generated by Django 5.1.1 on 2025-11-10 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0004_ingredientpurchase_menuitem_menuitembatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitembatch',
            name='ingredient_purchase_date',
        ),
        migrations.AddField(
            model_name='menuitembatch',
            name='prepared_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ingredientpurchase',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menuitembatch',
            name='weight_discarded',
            field=models.FloatField(default=0.0, help_text='Estimated discarded food weight (kg)'),
        ),
    ]
