# Generated by Django 5.1.1 on 2025-11-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0005_remove_menuitembatch_ingredient_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='shelf_life_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
